USE [master]
GO

/****** Object:  Database [AdventureWorks2012]    Script Date: 2018-02-24 09:58:46 ******/
CREATE DATABASE [AdventureWorks2012]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2012_Data', FILENAME = N'C:\Users\JINAN\DataBases\AdventureWorks2012_Data.mdf' , SIZE = 209920KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks2012_Log', FILENAME = N'C:\Users\JINAN\DataBases\AdventureWorks2012_Data_log.ldf' , SIZE = 1536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks2012].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdventureWorks2012] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET ANSI_NULLS ON 
GO

ALTER DATABASE [AdventureWorks2012] SET ANSI_PADDING ON 
GO

ALTER DATABASE [AdventureWorks2012] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [AdventureWorks2012] SET ARITHABORT ON 
GO

ALTER DATABASE [AdventureWorks2012] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AdventureWorks2012] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdventureWorks2012] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdventureWorks2012] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [AdventureWorks2012] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [AdventureWorks2012] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdventureWorks2012] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdventureWorks2012] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdventureWorks2012] SET  MULTI_USER 
GO

ALTER DATABASE [AdventureWorks2012] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdventureWorks2012] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdventureWorks2012] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdventureWorks2012] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AdventureWorks2012] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdventureWorks2012] SET QUERY_STORE = OFF
GO

USE [AdventureWorks2012]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [AdventureWorks2012]
GO

EXEC [AdventureWorks2012].sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorks 2012 Sample OLTP Database' 
GO

USE [master]
GO

ALTER DATABASE [AdventureWorks2012] SET  READ_WRITE 
GO


